version: '3.4'
services:
  app:
    build:
      args:
        user: app
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: test_machaon_app
    working_dir: /var/www/html
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - nginx
      - db
    networks:
      - test_machaon_network

  nginx:
    image: nginx:stable
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - "${APP_PORT}:80"
    container_name: test_machaon_nginx
    depends_on:
      - db
    networks:
      - test_machaon_network

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: machaon
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: test_machaon_db
    networks:
      - test_machaon_network

  pma:
    image: phpmyadmin:5.2
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: 3306
    depends_on:
      - db
    ports:
      - ${DB_PORT}:80
    container_name: test_machaon_pma
    networks:
      - test_machaon_network

networks:
  test_machaon_network:
    driver: bridge